[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
alloc = ["dep:axalloc"]
paging = ["alloc", "axhal/paging"]
multitask = ["alloc", "axtask/multitask"]

fs = ["alloc", "paging", "axdriver/virtio-blk", "dep:axfs"] # TODO: remove "paging"
net = ["alloc", "paging", "axdriver/virtio-net", "dep:axnet"]

default = []

[dependencies]
axalloc = { path = "../axalloc", optional = true }
axconfig = { path = "../axconfig" }
axdriver = { path = "../axdriver", optional = true }
axfs = { path = "../axfs", optional = true }
axhal = { path = "../axhal" }
axlog = { path = "../axlog" }
axnet = { path = "../axnet", optional = true }
axtask = { path = "../axtask", default-features = false, optional = true }
